### ISSUE TITLE
Demo TODO

### ISSUE THREAD

**Issue by LuxMiranda** [Cubium/Cubium#6]
We've got pretty much all of the Cubium backbone that we need for this demo! Now:

- [x] Create a "light sensor" component, a "temperature sensor" component, a median filter component, and a "solar array" component connected to the LSM
- [x] Have the median filter subscribe to light sensor and temperature sensor
- [x] Have solar array subscribe to median filter
- [x] Light, temp, and median filter spit out data appropriate for real time graphs
- [x] Solar array triggers the servo program at the appropriately arbitrary moment
