### ISSUE TITLE
Immediate TODO

### ISSUE THREAD

**Issue by LuxMiranda** [Cubium/Cubium#8]
- [x] Component A send subscription request to LSM
- [x] Successfully route subscription request to Component B (this may require some changes to how the LSM handles cubiumSockets)
- [x] Component B send subscription reply & successfully route
- [x] Ensure subscriptions are tracked and handled a la SPA standard
- [x] Have the subscribee component pump out dummy data in the form of SpaData messages
- [x] Make sure subscriber component gets it. Have the subscriber just spit it out with cout or something.
